### ISSUE TITLE
eos-mgm: Set `EOS_MGM_OIDC_MAP_FIELD` for OAuth mapping

### ISSUE THREAD

**Issue by ebocchi** [sciencebox/charts#26]
```
          env:
           {...cut...}
            - name: EOS_MGM_OIDC_MAP_FIELD
              value: "preferred_name"
```

Make sure `preferred_name` is actually _the_ good parameter to map users to
