### ISSUE TITLE
Remove custom hub image

### ISSUE THREAD

**Issue by ebocchi** [sciencebox/charts#30]
This should be removed
```
      image:
        name: "gitlab-registry.cern.ch/sciencebox/hotfixes/jupyterhub"
        tag: "v1.18-20220314"
        pullPolicy: "Always"
```
once the new version of the authenticator is part of the swan-provided container images
